use std::fs;
use std::io::Write;

fn main() {
    let mod_path = "src-tauri/src/commands/mod.rs";
    let content = fs::read_to_string(mod_path).expect("Unable to read file");
    
    let mut current_module = String::new();
    let mut modules: Vec<(String, Vec<String>)> = Vec::new();
    let mut imports: Vec<String> = Vec::new();
    
    let mut in_imports = true;
    
    for line in content.lines() {
        if line.starts_with("// Context Management Commands") {
            in_imports = false;
            current_module = "contexts".to_string();
            modules.push((current_module.clone(), Vec::new()));
        } else if line.starts_with("// Cluster Overview Commands") {
            current_module = "cluster".to_string();
            modules.push((current_module.clone(), Vec::new()));
        } else if line.starts_with("// Resource Commands") {
            current_module = "resources".to_string();
            modules.push((current_module.clone(), Vec::new()));
        } else if line.starts_with("// Deployment Commands") {
            current_module = "deployments".to_string();
            modules.push((current_module.clone(), Vec::new()));
        } else if line.starts_with("// StatefulSet Commands") {
            current_module = "statefulsets".to_string();
            modules.push((current_module.clone(), Vec::new()));
        } else if line.starts_with("// DaemonSet Commands") {
            current_module = "daemonsets".to_string();
            modules.push((current_module.clone(), Vec::new()));
        } else if line.starts_with("// ReplicaSet Commands") {
            current_module = "replicasets".to_string();
            modules.push((current_module.clone(), Vec::new()));
        } else if line.starts_with("// CronJob Commands") {
            current_module = "cronjobs".to_string();
            modules.push((current_module.clone(), Vec::new()));
        } else if line.starts_with("// Metrics Operations") || line.starts_with("// Metrics Commands") {
            current_module = "metrics".to_string();
            modules.push((current_module.clone(), Vec::new()));
        } else if line.starts_with("// Pod Operations") || line.starts_with("// Pod Actions") || line.starts_with("// Pod Commands") {
            current_module = "pods".to_string();
            modules.push((current_module.clone(), Vec::new()));
        } else if line.starts_with("// Watch Operations") || line.starts_with("// Watch Commands") {
            current_module = "watch".to_string();
            modules.push((current_module.clone(), Vec::new()));
        } else if line.starts_with("// Exec Commands") || line.starts_with("// Pod Exec Commands") {
            current_module = "exec".to_string();
            modules.push((current_module.clone(), Vec::new()));
        } else if line.starts_with("// Port Forwarding Commands") || line.starts_with("// Port Forward Commands") {
            current_module = "port_forward".to_string();
            modules.push((current_module.clone(), Vec::new()));
        }
        
        if in_imports {
            imports.push(line.to_string());
        } else {
            if let Some(last) = modules.last_mut() {
                last.1.push(line.to_string());
            }
        }
    }
    
    // Now write each module
    let mut mod_rs_content = String::new();
    mod_rs_content.push_str("// Auto-generated by split_mod.rs\n\n");
    
    for (name, lines) in &modules {
        let mut file_content = String::new();
        for import in &imports {
            file_content.push_str(import);
            file_content.push('\n');
        }
        file_content.push('\n');
        for line in lines {
            file_content.push_str(line);
            file_content.push('\n');
        }
        
        let file_path = format!("src-tauri/src/commands/{}.rs", name);
        fs::write(&file_path, file_content).expect("Failed to write module file");
        
        mod_rs_content.push_str(&format!("pub mod {};\n", name));
    }
    
    // And finally we would overwrite mod.rs (let's output it to a new file to verify first)
    fs::write("src-tauri/src/commands/mod_new.rs", mod_rs_content).expect("Failed to write mod_new.rs");
}
